app_url: http://localhost:3000
app_name: MaticArt NFT
app_logo: maticart.png
base_coin: MATIC
app_coin: WMATIC
auto_approval: true
mysql_username: matic
mysql_password: 'CHANGE_PASSWORD'
secret_key_base: b2d96dac611f4a65c84e5c85d16ec9cf90ddd88795d0a57a4fb207745dc9f81a0b4aa336f375dc5bfefb002ca72ba5164b645eb17c566cb5cceb7207d0b1c397
ethereum_provider: https://rpc-mumbai.maticvigil.com/
signer_private_key: 566d67584f632056216748630c62b5be4978d78f155b078ae1c7e77230c2a2b6 #Do not keep currencies to this address
free_minter_key: 566d67584f632056216748630c62b5be4978d78f155b078ae1c7e77230c2a2b6
coingecko_url: https://api.coingecko.com/api/v3/simple/price
contract_address:
  erc721: '0x428791F08ed8E555192C566b512A73df3b0b06FA'
gasstation_url: https://gasstation-mumbai.matic.today/v2
pinata:
  api_key: f7b6d1453e1edc1ebd2b
  api_secret: adfde89143ecdf2aa34e4658cd0d1eace6b7c8ab9de60ba39d2017bb6874fdc3
  base_url: https://api.pinata.cloud/pinning/pinFileToIPFS
default_fees:
  service_fee: 2.5
discussion_url: '#'
support_url: '#'
send_email: false # Send email or not
mailer_address: 'smtp.gmail.com' # Enter the server address for your SMTP server
mailer_port: 587 # Enter the port of your SMTP server
mailer_username: smtp_username # Enter your SMTP email username
mailer_password: smtp_password # Enter your SMTP email password
tls_auto: true
exception_sender: inbound.support@yourdomain.com # Enter your exception sender email
exception_recipients: ['support@yourdomain.com'] # Enter your exception recipients email
email_prefix: '[NFT] ' # Enter your exception email prefix
matic_url: https://mumbai.polygonscan.com
recent_hours: 48
