chainId: 137
wmaticAddress: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270'
transferProxyContractAddress: '0x73F5e8203F351B6ffC990d132089A1dBd91F19C6'
tradeContractAddress: '0xd3Fb6B280D42DE47fE7C902b665A233f8f4b45F4'
freeMinterPublicKey: '0xa505f0B53Df7da573c3aCC6162d49Bfb6a128c6C'
refundTransferPublicKey: '0x79663B6537FB61B7fB29b24D1414d71fD950657D'
